# ============================================================================
# Xoe-NovAi Phase 1 v0.1.2 Docker Compose Configuration (FIXED)
# ============================================================================
# Purpose: Multi-service orchestration for RAG stack with CrawlModule
# Guide Reference: Section 6 (Complete docker-compose.yml)
# Last Updated: 2025-10-13
# CRITICAL FIXES:
#   - Removed obsolete 'version' key (Compose v2)
#   - Removed cap_drop from Redis (conflicts with user 999)
#   - Updated volume mounts for library/ and knowledge/
# ============================================================================

services:
  # ==========================================================================
  # REDIS SERVICE - Cache & Streams Coordinator (7.4.1)
  # ==========================================================================
  redis:
    image: redis:7.4.1
    container_name: xnai_redis
    # Use native Redis command (NOT custom entrypoint)
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --tcp-backlog 2048
      --protected-mode no
      --dir /data
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_STREAM_MAX_LEN=${REDIS_STREAM_MAX_LEN:-1000}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
    networks:
      - xnai_network
    restart: unless-stopped
    # Redis runs as user 999:999 - don't drop capabilities
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:mode=1777,size=512m

  # ==========================================================================
  # RAG SERVICE - FastAPI Backend with LLM/FAISS
  # ==========================================================================
  rag:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: xnai_rag_api
    volumes:
      # Models (always bind mounts - large files)
      - ./models:/models:ro
      - ./embeddings:/embeddings:ro
      
      # Development: Bind mounts (default, comment for production)
      - ./library:/library                # Curated library (stack root)
      - ./knowledge:/knowledge            # Phase 2 agent knowledge (stack root)
      - ./data/faiss_index:/app/XNAi_rag_app/faiss_index
      - ./data/faiss_index.bak:/app/XNAi_rag_app/faiss_index.bak
      - ./backups:/backups                # FAISS backups
      
      # Production: Named volumes (uncomment for production)
      # - library:/library
      # - knowledge:/knowledge
      # - faiss_index:/app/XNAi_rag_app/faiss_index
      # - faiss_backup:/backups
      
      # Common mounts
      - ./data/prometheus-multiproc:/prometheus_data
      - ./app/XNAi_rag_app:/app/XNAi_rag_app
    environment:
      - RAG_API_URL=http://rag:8000
      - MODEL_PATH=/models/gemma-3-4b-it-UD-Q5_K_XL.gguf
      - EMBEDDING_MODEL_PATH=/embeddings/all-MiniLM-L12-v2.Q8_0.gguf
      - RAG_PER_DOC_CHARS=${RAG_PER_DOC_CHARS:-500}
      - RAG_TOTAL_CHARS=${RAG_TOTAL_CHARS:-2048}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CACHE_TTL=${REDIS_CACHE_TTL:-3600}
      - ERROR_RECOVERY_ENABLED=${ERROR_RECOVERY_ENABLED:-true}
      - BACKUP_ENABLED=${BACKUP_ENABLED:-true}
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}
    networks:
      - xnai_network
    ports:
      - "8000:8000"
      - "8002:8002"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python3", "/app/XNAi_rag_app/healthcheck.py"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 180s
    restart: unless-stopped
    user: "${APP_UID}:${APP_GID}"
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - CHOWN
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:mode=1777,size=512m

  # ==========================================================================
  # UI SERVICE - Chainlit Frontend
  # ==========================================================================
  ui:
    build:
      context: .
      dockerfile: Dockerfile.chainlit
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: xnai_chainlit_ui
    volumes:
      - ./app/XNAi_rag_app:/app/XNAi_rag_app
    environment:
      - CHAINLIT_PORT=${CHAINLIT_PORT}
      - CHAINLIT_NO_TELEMETRY=${CHAINLIT_NO_TELEMETRY}
      - RAG_API_URL=${RAG_API_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      rag:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
    networks:
      - xnai_network
    ports:
      - "8001:8001"
    restart: unless-stopped
    user: "${APP_UID}:${APP_GID}"
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:mode=1777,size=512m
      - /app/XNAi_rag_app/tmp:mode=1777,size=512m

  # ==========================================================================
  # CRAWLER SERVICE - CrawlModule v0.1.7 (NEW v0.1.2)
  # ==========================================================================
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawl
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: xnai_crawler
    volumes:
      # Development: Bind mounts (default, comment for production)
      - ./library:/library                # Write curated documents
      - ./knowledge:/knowledge            # Write metadata
      - ./data/cache:/app/cache           # Crawler cache
      
      # Production: Named volumes (uncomment for production)
      # - library:/library
      # - knowledge:/knowledge
      # - crawler_cache:/app/cache
      
      # Common mounts
      - ./app/XNAi_rag_app:/app/XNAi_rag_app
    environment:
      - CRAWL4AI_NO_TELEMETRY=${CRAWL4AI_NO_TELEMETRY:-true}
      - CRAWL4AI_MAX_DEPTH=${CRAWL4AI_MAX_DEPTH:-2}
      - CRAWL_RATE_LIMIT_PER_MIN=${CRAWL_RATE_LIMIT_PER_MIN:-30}
      - CRAWL_SANITIZE_SCRIPTS=${CRAWL_SANITIZE_SCRIPTS:-true}
      - CRAWL_MAX_ITEMS=${CRAWL_MAX_ITEMS:-50}
      - CRAWL_ALLOWLIST_URLS=${CRAWL_ALLOWLIST_URLS}
      - CRAWL_CACHE_DIR=/app/cache
      - CRAWL_CACHE_TTL=${CRAWL_CACHE_TTL:-86400}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
      rag:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python3", "-c", "import crawl4ai; print('OK')"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    networks:
      - xnai_network
    restart: unless-stopped
    user: "${APP_UID}:${APP_GID}"
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - CHOWN
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:mode=1777,size=512m

# ============================================================================
# NETWORKS
# ============================================================================
networks:
  xnai_network:
    driver: bridge
    name: xnai_network

# ============================================================================
# VOLUMES (Named Volumes for Production)
# ============================================================================
# Uncomment this section for production deployment
# Then comment bind mounts in services above and uncomment named volume mounts
#
# volumes:
#   library:
#     driver: local
#   knowledge:
#     driver: local
#   faiss_index:
#     driver: local
#   faiss_backup:
#     driver: local
#   crawler_cache:
#     driver: local
#   redis_data:
#     driver: local
#   prometheus_multiproc:
#     driver: local
#   logs:
#     driver: local

# ============================================================================
# PRODUCTION DEPLOYMENT INSTRUCTIONS
# ============================================================================
# 1. Create host directories:
#    mkdir -p library knowledge
#    chown 1001:1001 library knowledge
#
# 2. Create named volumes:
#    docker volume create xnai_library
#    docker volume create xnai_knowledge
#
# 3. Initialize volumes with data:
#    docker run --rm -v xnai_library:/library -v ./library:/host \
#      busybox sh -c "cp -r /host/* /library/"
#    docker run --rm -v xnai_knowledge:/knowledge -v ./knowledge:/host \
#      busybox sh -c "cp -r /host/* /knowledge/"
#
# 4. Update docker-compose.yml:
#    - Comment bind mount lines (./library:/library, etc.)
#    - Uncomment named volume lines (library:/library, etc.)
#    - Uncomment volumes section at bottom
#
# 5. Deploy:
#    docker compose down
#    docker compose up -d
#
# 6. Verify:
#    docker volume ls | grep xnai
#    docker inspect xnai_rag | grep -E "library|knowledge"
#    docker run --rm -v xnai_library:/library busybox ls -la /library
#
# ============================================================================