name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        pip install -r requirements-api.txt
        pip install -r requirements-chainlit.txt
        pip install -r requirements-crawl.txt
    - name: Run tests
      run: pytest --cov >90%
    - name: Validate config
      run: python3 scripts/validate_config.py
    - name: Benchmark
      run: make benchmark